import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const posts = trpc.posts.indexPost.useQuery();
  const addPost = trpc.posts.createPost.useMutation();

  const onAdd = () => {
    addPost.mutate({
      title: 'Cant believe!',
      body: 'it works'
    })
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {posts ? <p>{JSON.stringify(posts.data)}</p> : <p>Loading..</p>}
        </div>
        <button onClick={onAdd}>Add Post</button>
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

