name: CI

on:
  push:
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.16.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: creates .env file
      run: |
        touch .env
        echo DATABASE_URL='http://localhost:3000' >> .env
         echo NEXTAUTH_SECRET='' >> .env
          echo NEXTAUTH_URL='http://localhost:3000' >> .env
           echo GITHUB_CLIENT_ID='' >> .env
            echo GITHUB_CLIENT_SECRET='' >> .env
    - run: npm ci
    - run: npm run lint
