name: CI

on:
  push:
  pull_request:

env:
  DATABASE_URL: 'https://localhost:3000'
  NEXTAUTH_SECRET: ''
  NEXTAUTH_URL: 'https://localhost:3000'
  GITHUB_CLIENT_ID: ''
  GITHUB_CLIENT_SECRET: ''


jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.16.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
